"""Add fields release date and category to book

Revision ID: 73fa50b36594
Revises: 0b4adacd9915
Create Date: 2025-07-19 17:57:17.250154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fa50b36594'
down_revision = '0b4adacd9915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('release_date', sa.Date(), nullable=False))
    op.add_column('books', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'category')
    op.drop_column('books', 'release_date')
    # ### end Alembic commands ###
